CREATE TABLE tracked_section (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_index VARCHAR(20) NOT NULL,
    subject       VARCHAR(10) NOT NULL,
    term          VARCHAR(5)  NOT NULL,
    academic_year INT         NOT NULL,
    campus        VARCHAR(10) NOT NULL,
    is_open       BOOLEAN     NOT NULL DEFAULT FALSE,
    user_contact  VARCHAR(20) NOT NULL,
    owner_token   VARCHAR(36) NOT NULL
);

CREATE INDEX idx_tracked_section_owner_token ON tracked_section (owner_token);
CREATE INDEX idx_tracked_section_query ON tracked_section (subject, term, academic_year, campus);
